In [ ]:
!pip install chromadb sentence-transformers pandas tqdm openpyxl

Collecting chromadb
  Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.4)
Collecting pydantic-settings>=2.0 (from chromadb)
  Downloading pydantic_settings-2.14.2-py3-none-any.whl.metadata (3.4 kB)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.49.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.42.1)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.42.1)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading pypika-0.51.1-py2.py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.5 MB/s eta 0:00:00
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.81.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.25.1)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-36.0.2-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.20.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.2)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.5.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.43.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.43.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.43.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.43.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl.metadata (1.7 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.43.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-semantic-conventions==0.64b0 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.5)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Downloading chromadb-1.5.9-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 73.9 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 28.3 MB/s eta 0:00:00
Downloading build-1.5.0-py3-none-any.whl (26 kB)
Downloading kubernetes-36.0.2-py2.py3-none-any.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 78.9 MB/s eta 0:00:00
Downloading onnxruntime-1.27.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 61.2 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.43.0-py3-none-any.whl (19 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.43.0-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.43.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.1 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.43.0-py3-none-any.whl (178 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.9/178.9 kB 13.1 MB/s eta 0:00:00
Downloading opentelemetry_api-1.43.0-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 5.3 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.64b0-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 20.9 MB/s eta 0:00:00
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (71 kB)

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
import os
import glob

DATA_PATH = "/content/drive/MyDrive/Training"

print(os.listdir(DATA_PATH))

['02.라벨링데이터', '01.원천데이터']

In [ ]:
all_files = glob.glob(DATA_PATH + "/**/*", recursive=True)

real_files = [f for f in all_files if os.path.isfile(f)]

print("전체 파일 수:", len(real_files))
real_files[:20]

전체 파일 수: 32

['/content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_05.중학교 1학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_06.중학교 2학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_05.중학교 1학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_07.중학교 3학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_08.고등학교 1학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_08.고등학교 1학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_06.중학교 2학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_07.중학교 3학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/01.원천데이터/TS_02.초등학교 4학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/01.원천데이터/TS_01.초등학교 3학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/01.원천데이터/TS_01.초등학교 3학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/01.원천데이터/TS_02.초등학교 4학년_01.객관식.zip']

In [ ]:
from collections import Counter

exts = [os.path.splitext(f)[1] for f in real_files]

Counter(exts)

Counter({'.zip': 32})

In [ ]:
import zipfile

ZIP_FILES = [f for f in real_files if f.endswith(".zip")]

print("zip 파일 수:", len(ZIP_FILES))
ZIP_FILES[:10]

zip 파일 수: 32

['/content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_01.객관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_05.중학교 1학년_02.주관식.zip',
 '/content/drive/MyDrive/Training/02.라벨링데이터/TL_06.중학교 2학년_02.주관식.zip']

In [ ]:
EXTRACT_PATH = "/content/extracted_training"

for zip_path in ZIP_FILES:
    print("압축 해제 중:", zip_path)
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(EXTRACT_PATH)

print("압축 해제 완료")

압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_01.초등학교 3학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_03.초등학교 5학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_02.초등학교 4학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_04.초등학교 6학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_05.중학교 1학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_06.중학교 2학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_05.중학교 1학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_07.중학교 3학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_08.고등학교 1학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_08.고등학교 1학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_06.중학교 2학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/02.라벨링데이터/TL_07.중학교 3학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_02.초등학교 4학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_01.초등학교 3학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_01.초등학교 3학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_02.초등학교 4학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_03.초등학교 5학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_03.초등학교 5학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_04.초등학교 6학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_04.초등학교 6학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_05.중학교 1학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_05.중학교 1학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_06.중학교 2학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_06.중학교 2학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_07.중학교 3학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_07.중학교 3학년_02.주관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_08.고등학교 1학년_01.객관식.zip
압축 해제 중: /content/drive/MyDrive/Training/01.원천데이터/TS_08.고등학교 1학년_02.주관식.zip
압축 해제 완료

In [ ]:
DATA_PATH = EXTRACT_PATH

all_files = glob.glob(DATA_PATH + "/**/*", recursive=True)
real_files = [f for f in all_files if os.path.isfile(f)]

print("압축 해제 후 전체 파일 수:", len(real_files))
real_files[:20]

압축 해제 후 전체 파일 수: 32496

['/content/extracted_training/S3_중등_1_000042.png',
 '/content/extracted_training/S3_초등_4_007440.png',
 '/content/extracted_training/S3_초등_6_010960.png',
 '/content/extracted_training/S3_초등_6_017835.json',
 '/content/extracted_training/S3_초등_6_017882.json',
 '/content/extracted_training/S3_중등_1_003836.json',
 '/content/extracted_training/S3_초등_3_012582.json',
 '/content/extracted_training/S3_중등_3_015024.png',
 '/content/extracted_training/S3_초등_6_017831.json',
 '/content/extracted_training/S3_중등_2_001616.json',
 '/content/extracted_training/S3_초등_6_010527.png',
 '/content/extracted_training/S3_초등_6_010384.json',
 '/content/extracted_training/S3_초등_4_013527.png',
 '/content/extracted_training/S3_초등_5_004812.png',
 '/content/extracted_training/S3_초등_5_004425.png',
 '/content/extracted_training/S3_중등_2_001472.json',
 '/content/extracted_training/S3_중등_3_003269.png',
 '/content/extracted_training/S3_중등_2_002712.png',
 '/content/extracted_training/S3_중등_2_002367.png',
 '/content/extracted_training/S3_중등_1_016316.json']

In [ ]:
json_files = [f for f in real_files if f.endswith(".json")]

print("json 파일 수:", len(json_files))
json_files[:10]

json 파일 수: 16248

['/content/extracted_training/S3_초등_6_017835.json',
 '/content/extracted_training/S3_초등_6_017882.json',
 '/content/extracted_training/S3_중등_1_003836.json',
 '/content/extracted_training/S3_초등_3_012582.json',
 '/content/extracted_training/S3_초등_6_017831.json',
 '/content/extracted_training/S3_중등_2_001616.json',
 '/content/extracted_training/S3_초등_6_010384.json',
 '/content/extracted_training/S3_중등_2_001472.json',
 '/content/extracted_training/S3_중등_1_016316.json',
 '/content/extracted_training/S3_중등_2_001988.json']

In [ ]:
import json

sample_path = json_files[0]

with open(sample_path, "r", encoding="utf-8") as f:
    sample_data = json.load(f)

print(type(sample_data))

if isinstance(sample_data, dict):
    print(sample_data.keys())
else:
    print(sample_data[:1])

<class 'dict'>
dict_keys(['raw_data_info', 'source_data_info', 'learning_data_info'])

In [ ]:
sample_data

{'raw_data_info': {'raw_data_name': '8d64fe38-2dbd-486a-9248-c3d7c4ec0804',
  'date': '2024-11-12',
  'publisher': '2차 저작',
  'publication_year': '2024-11-01',
  'school': '초등학교',
  'grade': '6학년',
  'semester': '2학기',
  'subject': '수학',
  'revision_year': '2015'},
 'source_data_info': {'source_data_name': 'S3_초등_6_017835',
  '2009_achievement_standard': [' '],
  '2015_achievement_standard': ['[6수04-04] 비례식을 알고, 그 성질을 이해하며, 이를 활용하여 간단한 비례식을 풀 수 있다.'],
  '2022_achievement_standard': ['[6수02-04] 비례식을 알고, 그 성질을 이해하며, 이를 활용하여 간단한 비례식을 풀 수 있다.'],
  'level_of_difficulty': '하',
  'types_of_problems': '객관식'},
 'learning_data_info': [{'class_num': 1,
   'class_name': '문항(텍스트)',
   'class_info_list': [{'Type': 'Bounding_Box',
     'Type_value': [[13, 7.720000000000001, 437, 32.72]],
     'text_description': '0. 3:0. 7을 간단한 자연수의 비로 나타내세요.'}]},
  {'class_num': 1,
   'class_name': '정답(텍스트)',
   'class_info_list': [{'Type': 'Bounding_Box',
     'Type_value': [[12, 56.5, 77, 84.5]],
     'text_description': '① $3: 7$'}]},
  {'class_num': 1,
   'class_name': '오답(텍스트)',
   'class_info_list': [{'Type': 'Bounding_Box',
     'Type_value': [[12, 88.5, 80, 236.5]],
     'text_description': '② $1: 2$ ③ $3: 4$ ④ $2: 5$ ⑤ 5:8'}]},
  {'class_num': 2,
   'class_name': '해설(텍스트)',
   'class_info_list': [{'Type': 'Bounding_Box',
     'Type_value': [[2, 243.5, 439, 274.5]],
     'text_description': '0. 3과 0. 7을 각각 1 배하여 정수로 만듭니다.'},
    {'Type': 'Bounding_Box',
     'Type_value': [[7, 397.5, 623, 427.5]],
     'text_description': '따라서 0. 3:0. 7은 3:7로 간단한 자연수 비로 나타낼 수 있습니다.'}]},
  {'class_num': 1,
   'class_name': '해설(이미지)',
   'class_info_list': [{'Type': 'Bounding_Box',
     'Type_value': [[395, 300.5, 543, 378.5]],
     'text_description': '$\\begin{array}{l}0. 3 \\times 10=3 \\\\ 0. 7 \\times 10=7\\end{array}$'}]}]}

In [ ]:
import pandas as pd

dfs = []

for path in json_files:
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        temp_df = pd.json_normalize(data)
        temp_df["source_file"] = path
        dfs.append(temp_df)

    except Exception as e:
        print("로드 실패:", path, e)

df = pd.concat(dfs, ignore_index=True)

print("데이터 개수:", len(df))
df.head()

데이터 개수: 16248

,learning_data_info,raw_data_info.raw_data_name,raw_data_info.date,raw_data_info.publisher,raw_data_info.publication_year,raw_data_info.school,raw_data_info.grade,raw_data_info.semester,raw_data_info.subject,raw_data_info.revision_year,source_data_info.source_data_name,source_data_info.2009_achievement_standard,source_data_info.2015_achievement_standard,source_data_info.2022_achievement_standard,source_data_info.level_of_difficulty,source_data_info.types_of_problems,source_file
0,"[{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...",8d64fe38-2dbd-486a-9248-c3d7c4ec0804,2024-11-12,2차 저작,2024-11-01,초등학교,6학년,2학기,수학,2015,S3_초등_6_017835,[ ],"[[6수04-04] 비례식을 알고, 그 성질을 이해하며, 이를 활용하여 간단한 비례...","[[6수02-04] 비례식을 알고, 그 성질을 이해하며, 이를 활용하여 간단한 비례...",하,객관식,/content/extracted_training/S3_초등_6_017835.json
1,"[{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...",ce14dfa9-8ec9-417b-8e9f-95b4f130fcab,2024-11-12,2차 저작,2024-11-01,초등학교,6학년,1학기,수학,2015,S3_초등_6_017882,[ ],"[[6수01-14] ‘(자연수)÷(자연수)’, ‘(소수)÷(자연수)’에서 나눗셈의 ...",[[6수01-14] ‘(자연수)/(자연수)’에서 나눗셈의 몫을 소수로 나타낼 수 있...,하,객관식,/content/extracted_training/S3_초등_6_017882.json
2,"[{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...",42ea2519-cd34-4efb-bb4d-ae65cd175d41,2024-09-06,교학사,2015-03-01,중학교,1학년,공통,수학,2015,S3_중등_1_003836,[ ],[[9수04-09] 입체도형의 겉넓이와 부피를 구할 수 있다.],[[9수03-08] 입체도형의 겉넓이와 부피를 구할 수 있다.],하,주관식,/content/extracted_training/S3_중등_1_003836.json
3,"[{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...",2c45431b-564a-4bd0-bcca-a2cbbe2ad562,2024-10-23,교학사,2019-11-01,초등학교,3학년,2학기,수학,2015,S3_초등_3_012582,[ ],[[4수01-05] 곱하는 수가 한 자리 수 또는 두 자리 수인 곱셈의 계산 원리를...,[[4수01-04] 곱하는 수가 한 자리 수 또는 두 자리 수인 곱셈의 계산 원리를...,하,주관식,/content/extracted_training/S3_초등_3_012582.json
4,"[{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...",66dcc8f9-85f6-48ef-8ab3-382510ea5ba4,2024-11-12,2차 저작,2024-11-01,초등학교,6학년,2학기,수학,2015,S3_초등_6_017831,[ ],[[6수01-11] 분수의 나눗셈의 계산 원리를 이해하고 그 계산을 할 수 있다.],[[6수01-11] 분수의 나눗셈의 계산 원리를 탐구하고 그 계산을 할 수 있다.],하,객관식,/content/extracted_training/S3_초등_6_017831.json

In [ ]:
df.columns.tolist()

['learning_data_info',
 'raw_data_info.raw_data_name',
 'raw_data_info.date',
 'raw_data_info.publisher',
 'raw_data_info.publication_year',
 'raw_data_info.school',
 'raw_data_info.grade',
 'raw_data_info.semester',
 'raw_data_info.subject',
 'raw_data_info.revision_year',
 'source_data_info.source_data_name',
 'source_data_info.2009_achievement_standard',
 'source_data_info.2015_achievement_standard',
 'source_data_info.2022_achievement_standard',
 'source_data_info.level_of_difficulty',
 'source_data_info.types_of_problems',
 'source_file']

In [ ]:
df["learning_data_info"].iloc[0]

[{'class_num': 1,
  'class_name': '문항(텍스트)',
  'class_info_list': [{'Type': 'Bounding_Box',
    'Type_value': [[13, 7.720000000000001, 437, 32.72]],
    'text_description': '0. 3:0. 7을 간단한 자연수의 비로 나타내세요.'}]},
 {'class_num': 1,
  'class_name': '정답(텍스트)',
  'class_info_list': [{'Type': 'Bounding_Box',
    'Type_value': [[12, 56.5, 77, 84.5]],
    'text_description': '① $3: 7$'}]},
 {'class_num': 1,
  'class_name': '오답(텍스트)',
  'class_info_list': [{'Type': 'Bounding_Box',
    'Type_value': [[12, 88.5, 80, 236.5]],
    'text_description': '② $1: 2$ ③ $3: 4$ ④ $2: 5$ ⑤ 5:8'}]},
 {'class_num': 2,
  'class_name': '해설(텍스트)',
  'class_info_list': [{'Type': 'Bounding_Box',
    'Type_value': [[2, 243.5, 439, 274.5]],
    'text_description': '0. 3과 0. 7을 각각 1 배하여 정수로 만듭니다.'},
   {'Type': 'Bounding_Box',
    'Type_value': [[7, 397.5, 623, 427.5]],
    'text_description': '따라서 0. 3:0. 7은 3:7로 간단한 자연수 비로 나타낼 수 있습니다.'}]},
 {'class_num': 1,
  'class_name': '해설(이미지)',
  'class_info_list': [{'Type': 'Bounding_Box',
    'Type_value': [[395, 300.5, 543, 378.5]],
    'text_description': '$\\begin{array}{l}0. 3 \\times 10=3 \\\\ 0. 7 \\times 10=7\\end{array}$'}]}]

In [ ]:
import pprint

pprint.pprint(df["learning_data_info"].iloc[0], depth=5)

[{'class_info_list': [{'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '0. 3:0. 7을 간단한 자연수의 비로 나타내세요.'}],
  'class_name': '문항(텍스트)',
  'class_num': 1},
 {'class_info_list': [{'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '① $3: 7$'}],
  'class_name': '정답(텍스트)',
  'class_num': 1},
 {'class_info_list': [{'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '② $1: 2$ ③ $3: 4$ ④ $2: 5$ ⑤ 5:8'}],
  'class_name': '오답(텍스트)',
  'class_num': 1},
 {'class_info_list': [{'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '0. 3과 0. 7을 각각 1 배하여 정수로 만듭니다.'},
                      {'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '따라서 0. 3:0. 7은 3:7로 간단한 자연수 비로 나타낼 '
                                           '수 있습니다.'}],
  'class_name': '해설(텍스트)',
  'class_num': 2},
 {'class_info_list': [{'Type': 'Bounding_Box',
                       'Type_value': [[...]],
                       'text_description': '$\\begin{array}{l}0. 3 \\times '
                                           '10=3 \\\\ 0. 7 \\times '
                                           '10=7\\end{array}$'}],
  'class_name': '해설(이미지)',
  'class_num': 1}]

In [ ]:
df["text"] = df["learning_data_info"].astype(str)

df = df[df["text"].str.strip() != ""]

print("전처리 후 데이터 개수:", len(df))
df[["text"]].head()

전처리 후 데이터 개수: 16248

                                                text
0  [{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...
1  [{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...
2  [{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...
3  [{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...
4  [{'class_num': 1, 'class_name': '문항(텍스트)', 'cl...

In [ ]:
!pip install chromadb sentence-transformers tqdm

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.9)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.4)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.14.2)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.49.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.27.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.81.1)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.25.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (36.0.2)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.20.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.2)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.5.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-proto==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.64b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.5)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("c")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.86k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/442M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/495k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
import chromadb

DB_PATH = "/content/drive/MyDrive/chroma_problem_db"

client = chromadb.PersistentClient(path=DB_PATH)

collection = client.get_or_create_collection(
    name="problem_collection"
)

In [ ]:
metadata_cols = [
    "raw_data_info.school",
    "raw_data_info.grade",
    "raw_data_info.semester",
    "raw_data_info.subject",
    "source_data_info.level_of_difficulty",
    "source_data_info.types_of_problems",
    "source_data_info.2009_achievement_standard",
    "source_data_info.2015_achievement_standard",
    "source_data_info.2022_achievement_standard"
]

available_metadata_cols = [
    col for col in metadata_cols
    if col in df.columns
]

texts = df["text"].tolist()
ids = [f"problem_{i}" for i in range(len(texts))]

metadatas = []

for i, row in df.iterrows():
    metadata = {
        "source_file": str(row.get("source_file", ""))
    }

    for col in available_metadata_cols:
        metadata[col] = str(row.get(col, ""))

    metadatas.append(metadata)

print("문서 수:", len(texts))
print("메타데이터 컬럼:", available_metadata_cols)

문서 수: 16248
메타데이터 컬럼: ['raw_data_info.school', 'raw_data_info.grade', 'raw_data_info.semester', 'raw_data_info.subject', 'source_data_info.level_of_difficulty', 'source_data_info.types_of_problems', 'source_data_info.2009_achievement_standard', 'source_data_info.2015_achievement_standard', 'source_data_info.2022_achievement_standard']

In [ ]:
from tqdm import tqdm

batch_size = 100

for start in tqdm(range(0, len(texts), batch_size)):
    end = start + batch_size

    batch_texts = texts[start:end]
    batch_ids = ids[start:end]
    batch_metadatas = metadatas[start:end]

    batch_embeddings = model.encode(
        batch_texts,
        show_progress_bar=False
    ).tolist()

    collection.add(
        ids=batch_ids,
        documents=batch_texts,
        embeddings=batch_embeddings,
        metadatas=batch_metadatas
    )

100%|██████████| 163/163 [03:06<00:00,  1.15s/it]

In [ ]:
print("ChromaDB 저장 개수:", collection.count())
print("DB 저장 위치:", DB_PATH)

ChromaDB 저장 개수: 16248
DB 저장 위치: /content/drive/MyDrive/chroma_problem_db

In [ ]:
query = "초등학교 수학 문제"

query_embedding = model.encode([query]).tolist()

results = collection.query(
    query_embeddings=query_embedding,
    n_results=5
)

results

{'ids': [['problem_8180',
   'problem_13994',
   'problem_2957',
   'problem_6870',
   'problem_14978']],
 'embeddings': None,
 'documents': [['[{\'class_num\': 2, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[62.16, 7.6, 531.6, 115.14]], \'text_description\': \'6-1 다음은 어느 중학교 3학년 학생 10 명이 A, B 두 모 둠으로 나누어 수학 시험을 치른 결과를 나타낸 것이 다. 이때 보기 중 옳은 것울 모두 고르시오.\'}, {\'Type\': \'Bounding_Box\', \'Type_value\': [[73.85, 242.91, 519.22, 380.19]], \'text_description\': \'ㄱ. 두 모둠의 시험 점수의 평균은 같다. ㄴ. B 모둠의 시험 점수의 표준편차는 $\\\\sqrt{2}$ 점이다. ㄷ. B 모둠의 학생들의 수학 점수가 A 모둠의 학생들의 수학 점수보다 더 고르다.\'}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[53.21, 120.58, 539.86, 206.39]], \'text_description\': \'<div class="table_tabular " style="text-align: center"> <div class="inline-tabular"><table id="tabular"> <tbody> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: left; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">A 모둠 (점)</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">8</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">6</td> <td style="text-align: left; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> </tr> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: left; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">B 모둠 (점)</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">5</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">8</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">9</td> <td style="text-align: left; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">6</td> </tr> </tbody> </table> </div></div>\'}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[437.32, 848.6, 479.46, 872.93]], \'text_description\': \'ㄱ, ㄴ\'}]}, {\'class_num\': 1, \'class_name\': \'해설(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[26.07, 409.69, 500.76, 843.6]], \'text_description\': \'ㄱ. $(\\\\mathrm{A}$ 모둠의 평균 $)=\\\\frac{8+7+7+6+7}{5}=\\\\frac{35}{5}=7$ (점) (B 모둠의 평균) $=\\\\frac{7+5+8+9+6}{5}=\\\\frac{35}{5}=7$ (점) 따라서 두 모둠의 시험 점수의 평균은 같다. ㄴ. (B 모둠의 표준편차) \\\\[ =\\\\sqrt{\\\\frac{0^{2}+(-2)^{2}+1^{2}+2^{2}+(-1)^{2}}{5}}=\\\\sqrt{\\\\frac{10}{5}}=\\\\sqrt{2} \\\\text { (점) } \\\\] ㄷ. (A 모둠의 표준편차) \\\\[ =\\\\sqrt{\\\\frac{1^{2}+0^{2}+0^{2}+(-1)^{2}+0^{2}}{5}}=\\\\sqrt{\\\\frac{2}{5}}=\\\\frac{\\\\sqrt{10}}{5} \\\\text { (점) } \\\\] A 모둠의 표준편차가 B 모둠의 표준편차보다 작으므로 A 모둠의 학생들의 수학 점수가 B 모둠의 학생들의 수학 점수보다 더 고르다.\'}]}]',
   '[{\'class_num\': 1, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[15, 0.25, 541.25, 77.75]], \'text_description\': \'3 다음은 A, B, C, D. E 5 명의 학생들의 수학 점수를 나타낸 것이다. 이때 수학 점수의 분산을 구하시오.\'}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[53.75, 87.75, 546.25, 171.5]], \'text_description\': \'<div class="table_tabular " style="text-align: center"> <div class="inline-tabular"><table id="tabular"> <tbody> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: center; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">학생</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">A</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">B</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">C</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">D</td> <td style="text-align: center; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">E</td> </tr> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: center; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">수학 점수(점)</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">84</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">86</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">90</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">92</td> <td style="text-align: center; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">88</td> </tr> </tbody> </table> </div></div>\'}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[489.25, 346.5, 506.25, 377.75]], \'text_description\': \'$8$\'}]}, {\'class_num\': 1, \'class_name\': \'해설(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[40, 208.25, 445.5, 345.25]], \'text_description\': \'\\\\[ (\\\\text { 평균 })=\\\\frac{84+86+90+92+88}{5}=\\\\frac{440}{5}=88 \\\\text { (점) } \\\\] 이므로 \\\\[ (\\\\text { 분산 })=\\\\frac{(-4)^{2}+(-2)^{2}+2^{2}+4^{2}+0^{2}}{5}=\\\\frac{40}{5}=8 \\\\]\'}]}]',
   "[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 1.79, 539.41, 74.4]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[7.14, 338.79, 484.01, 403.54]], 'text_description': '② 국어와 수학의 점수가 같은 학생은 몇 명인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[1.71, 90.69, 253.73, 331.84]], 'text_description': '국어와 수학 점수의 산점도이다. 가로는 국어(점) 세로는 수학(점)이다. 가로 40 세로 60, 가로 60 세로 60, 가로 80 세로 80, 가로 100 세로 100을 잇는 선이 있다. 이 주변에 점들이 있다.'}]}, {'class_num': 1, 'class_name': '정답(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 454.59, 67.97, 482.83]], 'text_description': '② 5 명'}]}, {'class_num': 1, 'class_name': '해설(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 417.66, 350.4, 449.16]], 'text_description': '② 직선 위에 있는 점을 찾으면 5 명이다.'}]}]",
   '[{\'class_num\': 1, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[48.8, 39.12, 445.6, 148.72]], \'text_description\': "지은이는 \'함께 공부하는 수학\'이라는 모임을 만들어 매주 토요일마다 친구들과 함께 수학 공부를 한다. 다음은이 모임에 참여한 학생들의 대화 내용이다. 틀린 말을 한 학생을 고르시오."}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[49.21, 168.45, 443.96, 358.4]], \'text_description\': "초록테두리의 상자에 다음과 같은 대화가 들어 있다.\\n지은: 오늘은 지난주에 공부한 \'유리수와 순환소수\'에 대해 한 가지씩 말해 보도록 하자. 민지: 음, 내가 먼저 말할게. 모든 순환소수는 유리수야. 영호: 무한소수의 합은 항상 무한소수야. 태오: 유한소수의 합은 항상 유한소수야."}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[64.8, 430.32, 89.2, 443.52]], \'text_description\': \'영호\'}]}, {\'class_num\': 1, \'class_name\': \'해설(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[51.26, 368.13, 441.91, 427.01]], \'text_description\': \'$0 \\\\dot{3}+0. \\\\dot{6}=\\\\frac{1}{3}+\\\\frac{2}{3}=1$ 위의 예에서도 알 수 있듯이 두 무한소수의 합이 항상 무한소수가 되는 것은 아니다. 따라서 들린 말을 한 학생은 영호이다.\'}]}]',
   "[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[9.18, 0.92, 542.81, 75.6]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[10.54, 340.38, 485.78, 408.27]], 'text_description': '③ 수학 점수가 국어 점수보다 더 높은 학생은 몇 명 인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[3.75, 95.97, 248.16, 330.87]], 'text_description': '가로는 국어(점) 세로는 수학(점)이다 가로 40 세로 40, 가로 60 세로 60, 가로 80 세로 80, 가로 100 세로 100을 잇는 직선이 있다. 그 주변에 점들도 있다.'}]}, {'class_num': 1, 'class_name': '정답(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[-0.32, 469.37, 64.85, 493.81]], 'text_description': '③ 7 명'}]}, {'class_num': 1, 'class_name': '해설(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[3.75, 419.56, 405.67, 451.57]], 'text_description': '③ 직선의 왼쪽 위에 있는 점을 잦으면 7 명이다.'}]}]"]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']",
    'source_file': '/content/extracted_training/S3_중등_3_013116.json',
    'raw_data_info.semester': '2학기',
    'source_data_info.types_of_problems': '객관식',
    'raw_data_info.subject': '수학',
    'source_data_info.2009_achievement_standard': "[' ']",
    'raw_data_info.school': '중학교',
    'source_data_info.level_of_difficulty': '하',
    'raw_data_info.grade': '3학년',
    'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']"},
   {'raw_data_info.school': '중학교',
    'source_data_info.level_of_difficulty': '하',
    'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']",
    'raw_data_info.subject': '수학',
    'raw_data_info.semester': '2학기',
    'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']",
    'source_data_info.2009_achievement_standard': "[' ']",
    'source_file': '/content/extracted_training/S3_중등_3_013112.json',
    'source_data_info.types_of_problems': '주관식',
    'raw_data_info.grade': '3학년'},
   {'raw_data_info.subject': '수학',
    'raw_data_info.semester': '2학기',
    'source_file': '/content/extracted_training/S3_중등_3_013134.json',
    'source_data_info.level_of_difficulty': '하',
    'raw_data_info.school': '중학교',
    'source_data_info.2009_achievement_standard': "[' ']",
    'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']",
    'source_data_info.types_of_problems': '주관식',
    'raw_data_info.grade': '3학년',
    'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']"},
   {'source_data_info.2009_achievement_standard': "[' ']",
    'source_file': '/content/extracted_training/S3_중등_2_001386.json',
    'raw_data_info.school': '중학교',
    'raw_data_info.grade': '2학년',
    'source_data_info.2015_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 이해한다.']",
    'raw_data_info.subject': '수학',
    'source_data_info.level_of_difficulty': '하',
    'raw_data_info.semester': '1학기',
    'source_data_info.2022_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 설명할 수 있다.']",
    'source_data_info.types_of_problems': '객관식'},
   {'raw_data_info.subject': '수학',
    'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']",
    'source_data_info.level_of_difficulty': '하',
    'source_file': '/content/extracted_training/S3_중등_3_013135.json',
    'raw_data_info.school': '중학교',
    'source_data_info.2009_achievement_standard': "[' ']",
    'source_data_info.types_of_problems': '주관식',
    'raw_data_info.semester': '2학기',
    'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']",
    'raw_data_info.grade': '3학년'}]],
 'distances': [[121.55490112304688,
   130.30787658691406,
   131.35186767578125,
   131.61366271972656,
   131.73312377929688]]}

In [ ]:
print("ChromaDB 저장 개수:", collection.count())
print("DB 저장 위치:", DB_PATH)

ChromaDB 저장 개수: 16248
DB 저장 위치: /content/drive/MyDrive/chroma_problem_db

In [ ]:
query = "초등학교 수학 문제"

query_embedding = model.encode([query]).tolist()

results = collection.query(
    query_embeddings=query_embedding,
    n_results=5
)

results

{'ids': [['problem_8180',
   'problem_13994',
   'problem_2957',
   'problem_6870',
   'problem_14978']],
 'embeddings': None,
 'documents': [['[{\'class_num\': 2, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[62.16, 7.6, 531.6, 115.14]], \'text_description\': \'6-1 다음은 어느 중학교 3학년 학생 10 명이 A, B 두 모 둠으로 나누어 수학 시험을 치른 결과를 나타낸 것이 다. 이때 보기 중 옳은 것울 모두 고르시오.\'}, {\'Type\': \'Bounding_Box\', \'Type_value\': [[73.85, 242.91, 519.22, 380.19]], \'text_description\': \'ㄱ. 두 모둠의 시험 점수의 평균은 같다. ㄴ. B 모둠의 시험 점수의 표준편차는 $\\\\sqrt{2}$ 점이다. ㄷ. B 모둠의 학생들의 수학 점수가 A 모둠의 학생들의 수학 점수보다 더 고르다.\'}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[53.21, 120.58, 539.86, 206.39]], \'text_description\': \'<div class="table_tabular " style="text-align: center"> <div class="inline-tabular"><table id="tabular"> <tbody> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: left; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">A 모둠 (점)</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">8</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">6</td> <td style="text-align: left; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">7</td> </tr> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: left; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">B 모둠 (점)</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">7</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">5</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">8</td> <td style="text-align: left; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">9</td> <td style="text-align: left; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">6</td> </tr> </tbody> </table> </div></div>\'}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[437.32, 848.6, 479.46, 872.93]], \'text_description\': \'ㄱ, ㄴ\'}]}, {\'class_num\': 1, \'class_name\': \'해설(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[26.07, 409.69, 500.76, 843.6]], \'text_description\': \'ㄱ. $(\\\\mathrm{A}$ 모둠의 평균 $)=\\\\frac{8+7+7+6+7}{5}=\\\\frac{35}{5}=7$ (점) (B 모둠의 평균) $=\\\\frac{7+5+8+9+6}{5}=\\\\frac{35}{5}=7$ (점) 따라서 두 모둠의 시험 점수의 평균은 같다. ㄴ. (B 모둠의 표준편차) \\\\[ =\\\\sqrt{\\\\frac{0^{2}+(-2)^{2}+1^{2}+2^{2}+(-1)^{2}}{5}}=\\\\sqrt{\\\\frac{10}{5}}=\\\\sqrt{2} \\\\text { (점) } \\\\] ㄷ. (A 모둠의 표준편차) \\\\[ =\\\\sqrt{\\\\frac{1^{2}+0^{2}+0^{2}+(-1)^{2}+0^{2}}{5}}=\\\\sqrt{\\\\frac{2}{5}}=\\\\frac{\\\\sqrt{10}}{5} \\\\text { (점) } \\\\] A 모둠의 표준편차가 B 모둠의 표준편차보다 작으므로 A 모둠의 학생들의 수학 점수가 B 모둠의 학생들의 수학 점수보다 더 고르다.\'}]}]',
   '[{\'class_num\': 1, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[15, 0.25, 541.25, 77.75]], \'text_description\': \'3 다음은 A, B, C, D. E 5 명의 학생들의 수학 점수를 나타낸 것이다. 이때 수학 점수의 분산을 구하시오.\'}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[53.75, 87.75, 546.25, 171.5]], \'text_description\': \'<div class="table_tabular " style="text-align: center"> <div class="inline-tabular"><table id="tabular"> <tbody> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: center; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">학생</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">A</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">B</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">C</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">D</td> <td style="text-align: center; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top-style: solid !important; border-top-width: 1px !important; width: auto; vertical-align: middle; ">E</td> </tr> <tr style="border-top: none !important; border-bottom: none !important;"> <td style="text-align: center; border-left: none !important; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">수학 점수(점)</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">84</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">86</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">90</td> <td style="text-align: center; border-right-style: solid !important; border-right-width: 1px !important; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">92</td> <td style="text-align: center; border-bottom-style: solid !important; border-bottom-width: 1px !important; border-top: none !important; width: auto; vertical-align: middle; ">88</td> </tr> </tbody> </table> </div></div>\'}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[489.25, 346.5, 506.25, 377.75]], \'text_description\': \'$8$\'}]}, {\'class_num\': 1, \'class_name\': \'해설(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[40, 208.25, 445.5, 345.25]], \'text_description\': \'\\\\[ (\\\\text { 평균 })=\\\\frac{84+86+90+92+88}{5}=\\\\frac{440}{5}=88 \\\\text { (점) } \\\\] 이므로 \\\\[ (\\\\text { 분산 })=\\\\frac{(-4)^{2}+(-2)^{2}+2^{2}+4^{2}+0^{2}}{5}=\\\\frac{40}{5}=8 \\\\]\'}]}]',
   "[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 1.79, 539.41, 74.4]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[7.14, 338.79, 484.01, 403.54]], 'text_description': '② 국어와 수학의 점수가 같은 학생은 몇 명인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[1.71, 90.69, 253.73, 331.84]], 'text_description': '국어와 수학 점수의 산점도이다. 가로는 국어(점) 세로는 수학(점)이다. 가로 40 세로 60, 가로 60 세로 60, 가로 80 세로 80, 가로 100 세로 100을 잇는 선이 있다. 이 주변에 점들이 있다.'}]}, {'class_num': 1, 'class_name': '정답(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 454.59, 67.97, 482.83]], 'text_description': '② 5 명'}]}, {'class_num': 1, 'class_name': '해설(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 417.66, 350.4, 449.16]], 'text_description': '② 직선 위에 있는 점을 찾으면 5 명이다.'}]}]",
   '[{\'class_num\': 1, \'class_name\': \'문항(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[48.8, 39.12, 445.6, 148.72]], \'text_description\': "지은이는 \'함께 공부하는 수학\'이라는 모임을 만들어 매주 토요일마다 친구들과 함께 수학 공부를 한다. 다음은이 모임에 참여한 학생들의 대화 내용이다. 틀린 말을 한 학생을 고르시오."}]}, {\'class_num\': 1, \'class_name\': \'문항(이미지)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[49.21, 168.45, 443.96, 358.4]], \'text_description\': "초록테두리의 상자에 다음과 같은 대화가 들어 있다.\\n지은: 오늘은 지난주에 공부한 \'유리수와 순환소수\'에 대해 한 가지씩 말해 보도록 하자. 민지: 음, 내가 먼저 말할게. 모든 순환소수는 유리수야. 영호: 무한소수의 합은 항상 무한소수야. 태오: 유한소수의 합은 항상 유한소수야."}]}, {\'class_num\': 1, \'class_name\': \'정답(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[64.8, 430.32, 89.2, 443.52]], \'text_description\': \'영호\'}]}, {\'class_num\': 1, \'class_name\': \'해설(텍스트)\', \'class_info_list\': [{\'Type\': \'Bounding_Box\', \'Type_value\': [[51.26, 368.13, 441.91, 427.01]], \'text_description\': \'$0 \\\\dot{3}+0. \\\\dot{6}=\\\\frac{1}{3}+\\\\frac{2}{3}=1$ 위의 예에서도 알 수 있듯이 두 무한소수의 합이 항상 무한소수가 되는 것은 아니다. 따라서 들린 말을 한 학생은 영호이다.\'}]}]',
   "[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[9.18, 0.92, 542.81, 75.6]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[10.54, 340.38, 485.78, 408.27]], 'text_description': '③ 수학 점수가 국어 점수보다 더 높은 학생은 몇 명 인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[3.75, 95.97, 248.16, 330.87]], 'text_description': '가로는 국어(점) 세로는 수학(점)이다 가로 40 세로 40, 가로 60 세로 60, 가로 80 세로 80, 가로 100 세로 100을 잇는 직선이 있다. 그 주변에 점들도 있다.'}]}, {'class_num': 1, 'class_name': '정답(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[-0.32, 469.37, 64.85, 493.81]], 'text_description': '③ 7 명'}]}, {'class_num': 1, 'class_name': '해설(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[3.75, 419.56, 405.67, 451.57]], 'text_description': '③ 직선의 왼쪽 위에 있는 점을 잦으면 7 명이다.'}]}]"]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'raw_data_info.school': '중학교',
    'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']",
    'raw_data_info.subject': '수학',
    'raw_data_info.grade': '3학년',
    'source_data_info.types_of_problems': '객관식',
    'source_data_info.level_of_difficulty': '하',
    'source_file': '/content/extracted_training/S3_중등_3_013116.json',
    'source_data_info.2009_achievement_standard': "[' ']",
    'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']",
    'raw_data_info.semester': '2학기'},
   {'source_data_info.2009_achievement_standard': "[' ']",
    'raw_data_info.semester': '2학기',
    'raw_data_info.school': '중학교',
    'source_data_info.level_of_difficulty': '하',
    'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']",
    'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']",
    'raw_data_info.grade': '3학년',
    'raw_data_info.subject': '수학',
    'source_file': '/content/extracted_training/S3_중등_3_013112.json',
    'source_data_info.types_of_problems': '주관식'},
   {'source_data_info.2009_achievement_standard': "[' ']",
    'raw_data_info.semester': '2학기',
    'source_data_info.types_of_problems': '주관식',
    'raw_data_info.school': '중학교',
    'raw_data_info.subject': '수학',
    'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']",
    'source_file': '/content/extracted_training/S3_중등_3_013134.json',
    'raw_data_info.grade': '3학년',
    'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']",
    'source_data_info.level_of_difficulty': '하'},
   {'raw_data_info.subject': '수학',
    'source_data_info.2015_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 이해한다.']",
    'source_file': '/content/extracted_training/S3_중등_2_001386.json',
    'source_data_info.level_of_difficulty': '하',
    'raw_data_info.semester': '1학기',
    'source_data_info.types_of_problems': '객관식',
    'source_data_info.2022_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 설명할 수 있다.']",
    'source_data_info.2009_achievement_standard': "[' ']",
    'raw_data_info.school': '중학교',
    'raw_data_info.grade': '2학년'},
   {'source_data_info.level_of_difficulty': '하',
    'source_data_info.types_of_problems': '주관식',
    'source_file': '/content/extracted_training/S3_중등_3_013135.json',
    'source_data_info.2009_achievement_standard': "[' ']",
    'raw_data_info.grade': '3학년',
    'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']",
    'raw_data_info.subject': '수학',
    'raw_data_info.school': '중학교',
    'raw_data_info.semester': '2학기',
    'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']"}]],
 'distances': [[121.55490112304688,
   130.30787658691406,
   131.35186767578125,
   131.61366271972656,
   131.73312377929688]]}

In [ ]:
for i, doc in enumerate(results["documents"][0]):
    print(f"\n--- 검색 결과 {i+1} ---")
    print(doc[:500])
    print("metadata:", results["metadatas"][0][i])

--- 검색 결과 1 ---
[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[62.16, 7.6, 531.6, 115.14]], 'text_description': '6-1 다음은 어느 중학교 3학년 학생 10 명이 A, B 두 모 둠으로 나누어 수학 시험을 치른 결과를 나타낸 것이 다. 이때 보기 중 옳은 것울 모두 고르시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[73.85, 242.91, 519.22, 380.19]], 'text_description': 'ㄱ. 두 모둠의 시험 점수의 평균은 같다. ㄴ. B 모둠의 시험 점수의 표준편차는 $\\sqrt{2}$ 점이다. ㄷ. B 모둠의 학생들의 수학 점수가 A 모둠의 학생들의 수학 점수보다 더 고르다.'}]}, {'class_num': 1, 'class_name': '문항(이미지)',
metadata: {'raw_data_info.school': '중학교', 'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']", 'raw_data_info.subject': '수학', 'raw_data_info.grade': '3학년', 'source_data_info.types_of_problems': '객관식', 'source_data_info.level_of_difficulty': '하', 'source_file': '/content/extracted_training/S3_중등_3_013116.json', 'source_data_info.2009_achievement_standard': "[' ']", 'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']", 'raw_data_info.semester': '2학기'}

--- 검색 결과 2 ---
[{'class_num': 1, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[15, 0.25, 541.25, 77.75]], 'text_description': '3 다음은 A, B, C, D. E 5 명의 학생들의 수학 점수를 나타낸 것이다. 이때 수학 점수의 분산을 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[53.75, 87.75, 546.25, 171.5]], 'text_description': '<div class="table_tabular " style="text-align: center"> <div class="inline-tabular"><table id="tabular"> <tbody> <tr style
metadata: {'source_data_info.2009_achievement_standard': "[' ']", 'raw_data_info.semester': '2학기', 'raw_data_info.school': '중학교', 'source_data_info.level_of_difficulty': '하', 'source_data_info.2022_achievement_standard': "['[9수04-07] 분산과 표준편차를 구하고 자료의 분포를 설명할 수 있다.']", 'source_data_info.2015_achievement_standard': "['[9수05-07] 분산과 표준편차의 의미를 이해하고, 이를 구할 수 있다.']", 'raw_data_info.grade': '3학년', 'raw_data_info.subject': '수학', 'source_file': '/content/extracted_training/S3_중등_3_013112.json', 'source_data_info.types_of_problems': '주관식'}

--- 검색 결과 3 ---
[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[8.23, 1.79, 539.41, 74.4]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[7.14, 338.79, 484.01, 403.54]], 'text_description': '② 국어와 수학의 점수가 같은 학생은 몇 명인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[1.71, 90.69, 253.73, 331.84]], 'text_description': '국어와 수
metadata: {'source_data_info.2009_achievement_standard': "[' ']", 'raw_data_info.semester': '2학기', 'source_data_info.types_of_problems': '주관식', 'raw_data_info.school': '중학교', 'raw_data_info.subject': '수학', 'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']", 'source_file': '/content/extracted_training/S3_중등_3_013134.json', 'raw_data_info.grade': '3학년', 'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']", 'source_data_info.level_of_difficulty': '하'}

--- 검색 결과 4 ---
[{'class_num': 1, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[48.8, 39.12, 445.6, 148.72]], 'text_description': "지은이는 '함께 공부하는 수학'이라는 모임을 만들어 매주 토요일마다 친구들과 함께 수학 공부를 한다. 다음은이 모임에 참여한 학생들의 대화 내용이다. 틀린 말을 한 학생을 고르시오."}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[49.21, 168.45, 443.96, 358.4]], 'text_description': "초록테두리의 상자에 다음과 같은 대화가 들어 있다.\n지은: 오늘은 지난주에 공부한 '유리수와 순환소수'에 대해 한 가지씩 말해 보도록 하자. 민지
metadata: {'raw_data_info.subject': '수학', 'source_data_info.2015_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 이해한다.']", 'source_file': '/content/extracted_training/S3_중등_2_001386.json', 'source_data_info.level_of_difficulty': '하', 'raw_data_info.semester': '1학기', 'source_data_info.types_of_problems': '객관식', 'source_data_info.2022_achievement_standard': "['[9수01-06] 순환소수의 뜻을 알고, 유리수와 순환소수의 관계를 설명할 수 있다.']", 'source_data_info.2009_achievement_standard': "[' ']", 'raw_data_info.school': '중학교', 'raw_data_info.grade': '2학년'}

--- 검색 결과 5 ---
[{'class_num': 2, 'class_name': '문항(텍스트)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[9.18, 0.92, 542.81, 75.6]], 'text_description': '02 오른쪽은 우리반 학생 15 명의 국어와 수학 점수의 산점도이다. 다음 물음에 답하시오.'}, {'Type': 'Bounding_Box', 'Type_value': [[10.54, 340.38, 485.78, 408.27]], 'text_description': '③ 수학 점수가 국어 점수보다 더 높은 학생은 몇 명 인지 구하시오.'}]}, {'class_num': 1, 'class_name': '문항(이미지)', 'class_info_list': [{'Type': 'Bounding_Box', 'Type_value': [[3.75, 95.97, 248.16, 330.87]], 'text_description':
metadata: {'source_data_info.level_of_difficulty': '하', 'source_data_info.types_of_problems': '주관식', 'source_file': '/content/extracted_training/S3_중등_3_013135.json', 'source_data_info.2009_achievement_standard': "[' ']", 'raw_data_info.grade': '3학년', 'source_data_info.2015_achievement_standard': "['[9수05-08] 자료를 산점도로 나타내고, 이를 이용하여 상관관계를 말할 수 있다.']", 'raw_data_info.subject': '수학', 'raw_data_info.school': '중학교', 'raw_data_info.semester': '2학기', 'source_data_info.2022_achievement_standard': "['[9수04-09] 자료를 산점도로 나타내고 상관관계를 말할 수 있다.']"}

In [ ]:
import os

os.listdir("/content/drive/MyDrive")

['How to get started with Drive.pdf',
 '제목 없는 문서 (1).gdoc',
 '젤로스 약학 2조 - 진통제.gdoc',
 '사본: 11002 김가영 요약본.gdoc',
 '사본: 11002 김가영 요약본.docx',
 '11002 김가영 요약본.gdoc',
 '11002 김가영 요약본.docx',
 '11002 김가영.mp4',
 '제목 없는 문서.gdoc',
 'A580094E-EB1E-4E58-A786-16295DE171ED.jpeg',
 'A93C2A1F-3652-4FAA-946F-57ABCB237FCB.jpeg',
 'IMG_6599.png',
 'Taewon & Gayoung & Jihoo - India (ppt).pptx',
 '논리와사고 분석보고서 과제 c511010 김가영 .gdoc',
 '인공지능 챗봇과의 감정 교류 가능성에 관한 설문조사 .gform',
 '인공지능 챗봇과의 감정 교류 가능성에 관한 설문조사 (응답).gsheet',
 'IMG_5293.png',
 'RECORD_20260227220316.mp4',
 'RECORD_20260306214020.mp4',
 'RECORD_20260310222527.mp4',
 'RECORD_20260314214531.mp4',
 'RECORD_20260317220158.mp4',
 'Colab Notebooks',
 '제목 없는 설문지 (File responses)',
 '제목 없는 설문지.gform',
 'RECORD_20260324220037.mp4',
 'RECORD_20260331220743.mp4',
 'RECORD_20260407220009.mp4',
 'RECORD_20260405211837.mp4',
 'RECORD_20260414220214.mp4',
 'AISLab_연구원지원서의 사본 (1).gdoc',
 'AI 미션 코스 Week 2.ipynb',
 'AISLab_연구원지원서의 사본.gdoc',
 'AISLab_학부연구원 지원서_C511010 김가영.gdoc',
 'Did AI Really Understand Van Gogh? (1).gslides',
 'Did AI Really Understand Van Gogh?.gslides',
 'Training',
 'chroma_problem_db']